/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const WhitePatchInput = IDL.Record({
  'x' : IDL.Float64,
  'y' : IDL.Float64,
  'height' : IDL.Float64,
  'width' : IDL.Float64,
});
export const TextureFeatures = IDL.Record({
  'homogeneity' : IDL.Float64,
  'contrast' : IDL.Float64,
  'energy' : IDL.Float64,
});
export const EdgeFeatures = IDL.Record({
  'edgeStrength' : IDL.Float64,
  'edgeDensity' : IDL.Float64,
  'arcusRingScore' : IDL.Float64,
});
export const RegionScore = IDL.Record({
  'region' : IDL.Text,
  'contrast' : IDL.Float64,
  'avgB' : IDL.Float64,
  'avgG' : IDL.Float64,
  'avgR' : IDL.Float64,
  'brightness' : IDL.Float64,
  'textureFeatures' : IDL.Opt(TextureFeatures),
  'edgeFeatures' : IDL.Opt(EdgeFeatures),
});
export const WhitePatchRegion = IDL.Record({
  'x' : IDL.Float64,
  'y' : IDL.Float64,
  'height' : IDL.Float64,
  'avgB' : IDL.Float64,
  'avgG' : IDL.Float64,
  'avgR' : IDL.Float64,
  'width' : IDL.Float64,
});
export const RegionBox = IDL.Record({
  'h' : IDL.Float64,
  'w' : IDL.Float64,
  'x' : IDL.Float64,
  'y' : IDL.Float64,
});
export const DetectedRegions = IDL.Record({
  'sclera' : RegionBox,
  'pupilCenter' : IDL.Tuple(IDL.Float64, IDL.Float64),
  'cornea' : RegionBox,
  'conjunctiva' : RegionBox,
  'irisRadius' : IDL.Float64,
});
export const SegmentationResult = IDL.Record({
  'irisFraction' : IDL.Float64,
  'irisRadiusEstimate' : IDL.Float64,
  'scleraFraction' : IDL.Float64,
});
export const Timestamp = IDL.Int;
export const FeatureConfidences = IDL.Record({
  'edge' : IDL.Float64,
  'color' : IDL.Float64,
  'segmentation' : IDL.Float64,
  'texture' : IDL.Float64,
});
export const ConditionResult = IDL.Record({
  'explanation' : IDL.Text,
  'score' : IDL.Float64,
  'conditionConfidence' : IDL.Float64,
  'riskLevel' : IDL.Text,
  'featureConfidences' : FeatureConfidences,
  'condition' : IDL.Text,
});
export const ImageId = IDL.Text;
export const AnalysisResult = IDL.Record({
  'detectionQuality' : IDL.Text,
  'regionScores' : IDL.Vec(RegionScore),
  'whitePatchUsed' : WhitePatchRegion,
  'detectedRegions' : IDL.Opt(DetectedRegions),
  'segmentationResult' : IDL.Opt(SegmentationResult),
  'timestamp' : Timestamp,
  'conditions' : IDL.Vec(ConditionResult),
  'imageId' : ImageId,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ScreeningId = IDL.Text;
export const ScreeningRecord = IDL.Record({
  'id' : ScreeningId,
  'result' : AnalysisResult,
  'imageStorageId' : IDL.Text,
  'userId' : IDL.Principal,
  'timestamp' : Timestamp,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'analyzeEyeImage' : IDL.Func(
      [ExternalBlob, WhitePatchInput],
      [AnalysisResult],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearHistory' : IDL.Func([], [IDL.Bool], []),
  'deleteScreening' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'generateSummary' : IDL.Func([IDL.Vec(ConditionResult)], [IDL.Text], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getScreening' : IDL.Func([IDL.Text], [IDL.Opt(ScreeningRecord)], ['query']),
  'getScreeningHistory' : IDL.Func([], [IDL.Vec(ScreeningRecord)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveScreening' : IDL.Func([AnalysisResult, IDL.Text], [IDL.Text], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const WhitePatchInput = IDL.Record({
    'x' : IDL.Float64,
    'y' : IDL.Float64,
    'height' : IDL.Float64,
    'width' : IDL.Float64,
  });
  const TextureFeatures = IDL.Record({
    'homogeneity' : IDL.Float64,
    'contrast' : IDL.Float64,
    'energy' : IDL.Float64,
  });
  const EdgeFeatures = IDL.Record({
    'edgeStrength' : IDL.Float64,
    'edgeDensity' : IDL.Float64,
    'arcusRingScore' : IDL.Float64,
  });
  const RegionScore = IDL.Record({
    'region' : IDL.Text,
    'contrast' : IDL.Float64,
    'avgB' : IDL.Float64,
    'avgG' : IDL.Float64,
    'avgR' : IDL.Float64,
    'brightness' : IDL.Float64,
    'textureFeatures' : IDL.Opt(TextureFeatures),
    'edgeFeatures' : IDL.Opt(EdgeFeatures),
  });
  const WhitePatchRegion = IDL.Record({
    'x' : IDL.Float64,
    'y' : IDL.Float64,
    'height' : IDL.Float64,
    'avgB' : IDL.Float64,
    'avgG' : IDL.Float64,
    'avgR' : IDL.Float64,
    'width' : IDL.Float64,
  });
  const RegionBox = IDL.Record({
    'h' : IDL.Float64,
    'w' : IDL.Float64,
    'x' : IDL.Float64,
    'y' : IDL.Float64,
  });
  const DetectedRegions = IDL.Record({
    'sclera' : RegionBox,
    'pupilCenter' : IDL.Tuple(IDL.Float64, IDL.Float64),
    'cornea' : RegionBox,
    'conjunctiva' : RegionBox,
    'irisRadius' : IDL.Float64,
  });
  const SegmentationResult = IDL.Record({
    'irisFraction' : IDL.Float64,
    'irisRadiusEstimate' : IDL.Float64,
    'scleraFraction' : IDL.Float64,
  });
  const Timestamp = IDL.Int;
  const FeatureConfidences = IDL.Record({
    'edge' : IDL.Float64,
    'color' : IDL.Float64,
    'segmentation' : IDL.Float64,
    'texture' : IDL.Float64,
  });
  const ConditionResult = IDL.Record({
    'explanation' : IDL.Text,
    'score' : IDL.Float64,
    'conditionConfidence' : IDL.Float64,
    'riskLevel' : IDL.Text,
    'featureConfidences' : FeatureConfidences,
    'condition' : IDL.Text,
  });
  const ImageId = IDL.Text;
  const AnalysisResult = IDL.Record({
    'detectionQuality' : IDL.Text,
    'regionScores' : IDL.Vec(RegionScore),
    'whitePatchUsed' : WhitePatchRegion,
    'detectedRegions' : IDL.Opt(DetectedRegions),
    'segmentationResult' : IDL.Opt(SegmentationResult),
    'timestamp' : Timestamp,
    'conditions' : IDL.Vec(ConditionResult),
    'imageId' : ImageId,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ScreeningId = IDL.Text;
  const ScreeningRecord = IDL.Record({
    'id' : ScreeningId,
    'result' : AnalysisResult,
    'imageStorageId' : IDL.Text,
    'userId' : IDL.Principal,
    'timestamp' : Timestamp,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'analyzeEyeImage' : IDL.Func(
        [ExternalBlob, WhitePatchInput],
        [AnalysisResult],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearHistory' : IDL.Func([], [IDL.Bool], []),
    'deleteScreening' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'generateSummary' : IDL.Func([IDL.Vec(ConditionResult)], [IDL.Text], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getScreening' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(ScreeningRecord)],
        ['query'],
      ),
    'getScreeningHistory' : IDL.Func([], [IDL.Vec(ScreeningRecord)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveScreening' : IDL.Func([AnalysisResult, IDL.Text], [IDL.Text], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };