/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AnalysisResult {
  'detectionQuality' : string,
  'regionScores' : Array<RegionScore>,
  'whitePatchUsed' : WhitePatchRegion,
  'detectedRegions' : [] | [DetectedRegions],
  'segmentationResult' : [] | [SegmentationResult],
  'timestamp' : Timestamp,
  'conditions' : Array<ConditionResult>,
  'imageId' : ImageId,
}
export interface ConditionResult {
  'explanation' : string,
  'score' : number,
  'conditionConfidence' : number,
  'riskLevel' : string,
  'featureConfidences' : FeatureConfidences,
  'condition' : string,
}
export interface DetectedRegions {
  'sclera' : RegionBox,
  'pupilCenter' : [number, number],
  'cornea' : RegionBox,
  'conjunctiva' : RegionBox,
  'irisRadius' : number,
}
export interface EdgeFeatures {
  'edgeStrength' : number,
  'edgeDensity' : number,
  'arcusRingScore' : number,
}
export type ExternalBlob = Uint8Array;
export interface FeatureConfidences {
  'edge' : number,
  'color' : number,
  'segmentation' : number,
  'texture' : number,
}
export type ImageId = string;
export interface RegionBox {
  'h' : number,
  'w' : number,
  'x' : number,
  'y' : number,
}
export interface RegionScore {
  'region' : string,
  'contrast' : number,
  'avgB' : number,
  'avgG' : number,
  'avgR' : number,
  'brightness' : number,
  'textureFeatures' : [] | [TextureFeatures],
  'edgeFeatures' : [] | [EdgeFeatures],
}
export type ScreeningId = string;
export interface ScreeningRecord {
  'id' : ScreeningId,
  'result' : AnalysisResult,
  'imageStorageId' : string,
  'userId' : Principal,
  'timestamp' : Timestamp,
}
export interface SegmentationResult {
  'irisFraction' : number,
  'irisRadiusEstimate' : number,
  'scleraFraction' : number,
}
export interface TextureFeatures {
  'homogeneity' : number,
  'contrast' : number,
  'energy' : number,
}
export type Timestamp = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WhitePatchInput {
  'x' : number,
  'y' : number,
  'height' : number,
  'width' : number,
}
export interface WhitePatchRegion {
  'x' : number,
  'y' : number,
  'height' : number,
  'avgB' : number,
  'avgG' : number,
  'avgR' : number,
  'width' : number,
}
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'analyzeEyeImage' : ActorMethod<
    [ExternalBlob, WhitePatchInput],
    AnalysisResult
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearHistory' : ActorMethod<[], boolean>,
  'deleteScreening' : ActorMethod<[string], boolean>,
  'generateSummary' : ActorMethod<[Array<ConditionResult>], string>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getScreening' : ActorMethod<[string], [] | [ScreeningRecord]>,
  'getScreeningHistory' : ActorMethod<[], Array<ScreeningRecord>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveScreening' : ActorMethod<[AnalysisResult, string], string>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];